modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Hide%20Hands"
logoFile="icon.png"

[[mods]]
modId="hidehands"
version="4.0"
displayName="Hide Hands"
displayURL="https://curseforge.com/minecraft/mc-mods/hide-hands"
authors="Rick South"
description='''Hide your offhand and/or mainhand, always or while holding specific items.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  
Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, Tyler Behl, Wendi S   
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.hidehands]]
    modId="collective"
    mandatory=true
    versionRange="[6.18,)"
    ordering="NONE"
    side="BOTH"